version: "2"

run:
  skip-dirs: ["build", "data", ".github"]

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
