#!/usr/bin/env bash
set -euo pipefail

# Installs the pre-commit hook in .git/hooks/pre-commit
HOOK_PATH=".git/hooks/pre-commit"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PRE_SCRIPT="$SCRIPT_DIR/pre-commit.sh"

if [ ! -d ".git" ]; then
  echo "Not a git repository (no .git directory found). Run from the repo root." >&2
  exit 1
fi

if [ ! -x "$PRE_SCRIPT" ]; then
  echo "Making pre-commit script executable: $PRE_SCRIPT"
  chmod +x "$PRE_SCRIPT"
fi

cat > "$HOOK_PATH" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hook.sh
exec "$(pwd)/scripts/pre-commit.sh" "$@"
HOOK

chmod +x "$HOOK_PATH"

echo "Installed pre-commit hook at $HOOK_PATH"
